import React from 'react';
import { treeRender } from './TreeRender';
const data = [
  {
    children: [
      {
        children: [
          {
            children: [],
            isRoot: false,
            id: 'u_tian_qi_xin_qing',
            path: '/u_tian_qi_xin_qing',
            title: '天气心情',
            isExpanded: false,
            styleType: 'menu',
            type: '',
            pid: 'wg5boclins9i',
            isActive: false,
            level: 1,
          },
        ],
        iconUrl:
          'https://6c6f-lowcode-8gr4tbore6df2c6a-1306806780.tcb.qcloud.la/weda-adminportal/upload/2021-12-08/cf1e5h0qsar9vkof46w51b570wxm0xrh_.jpeg?sign=36534f91e680b4aa97b9101ffc74ba11&t=1638959502',
        isRoot: true,
        id: 'wg5boclins9i',
        title: '11',
        type: 'group',
        isExpanded: false,
        styleType: 'group',
        pid: 0,
        isActive: false,
        level: 0,
      },
    ],
    isRoot: true,
    id: 'test1101_hlz2igq_list',
    path: '/test1101_hlz2igq_list',
    title: '天气心情日志列表',
    isExpanded: false,
    styleType: 'menu',
    type: '',
    pid: 0,
    isActive: false,
    level: 0,
    expanded: true,
  },
  {
    children: [],
    iconUrl:
      'https://6c6f-lowcode-8gr4tbore6df2c6a-1306806780.tcb.qcloud.la/weda-adminportal/upload/2021-12-10/tugljmh962bf55ppzo4sqlm0no97h16z_.jpeg?sign=9d8fa3f3abbdd46317fb0fdac1f21e3b&t=1639107124',
    isRoot: true,
    id: 'dka3exsakvm9',
    title: '111',
    type: 'group',
    isExpanded: false,
    styleType: 'group',
    pid: 0,
    isActive: false,
    level: 0,
  },
  {
    children: [
      {
        children: [
          {
            children: [],
            iconUrl:
              'https://6c6f-lowcode-8gr4tbore6df2c6a-1306806780.tcb.qcloud.la/weda-adminportal/upload/2021-12-08/t9oycuax3kb65jr6ud9op1vuow9ho0uq_.jpeg?sign=1cdc765cbd5590c4b0ed663b239feb9c&t=1638959517',
            isRoot: false,
            id: 'test1101_hlz2igq_create',
            path: '/test1101_hlz2igq_create',
            title: '创建天气心情日志',
            isExpanded: false,
            type: '',
            level: 2,
            isActive: false,
          },
        ],
        iconUrl:
          'https://6c6f-lowcode-8gr4tbore6df2c6a-1306806780.tcb.qcloud.la/weda-adminportal/upload/2021-12-10/72s6ojob2s8o0m99e19efhawxf4cqa7k_.jpeg?sign=5f1163db4d9ccce3b005f8a6ada9b070&t=1639108074',
        isRoot: false,
        id: 'l6ec7wim00co',
        title: '22',
        type: 'basemenu',
        isExpanded: false,
        styleType: 'submenu',
        pid: 'vaigx38gavke',
        isActive: false,
        level: 1,
      },
    ],
    isRoot: true,
    id: 'vaigx38gavke',
    title: '11',
    type: 'group',
    isExpanded: false,
    styleType: 'group',
    pid: 0,
    isActive: false,
    level: 0,
  },
  {
    children: [
      {
        children: [],
        isRoot: false,
        id: '1fv8y3x4eia1',
        path: 'https://www.baidu.com/',
        title: 'wrwr',
        type: 'link',
        isExpanded: false,
        styleType: 'menu',
        pid: 'e6zjiptoojrh',
        isActive: false,
        level: 1,
      },
    ],
    iconUrl:
      'https://6c6f-lowcode-8gr4tbore6df2c6a-1306806780.tcb.qcloud.la/weda-adminportal/upload/2021-12-10/83xchz843xa05ouih31j3ifyw7eagtyv_.jpeg?sign=01b1d0866eb2ed46a9e39eaeac5e7a9b&t=1639108750',
    isRoot: true,
    id: 'e6zjiptoojrh',
    title: 'ffeww',
    type: 'group',
    isExpanded: false,
    styleType: 'group',
    pid: 0,
    isActive: false,
    level: 0,
  },
  {
    children: [],
    isRoot: true,
    id: 'f34c3df7hms2',
    path: '11',
    title: '453534',
    type: 'link',
    isExpanded: false,
    styleType: 'menu',
    pid: 0,
    isActive: false,
    level: 0,
  },
  {
    children: [
      {
        children: [
          {
            children: [],
            isRoot: false,
            id: 'in7wkeksugia',
            title: '121212',
            type: '',
            isExpanded: false,
            level: 2,
            isActive: false,
          },
          {
            children: [],
            isRoot: false,
            id: 'geedv3oz858f',
            title: '11221',
            type: '',
            isExpanded: false,
            level: 2,
            isActive: false,
          },
          {
            children: [],
            isRoot: false,
            id: '2fwc6ljbmwdp',
            title: 'ddd',
            type: '',
            isExpanded: false,
            level: 2,
            isActive: false,
          },
          {
            children: [],
            isRoot: false,
            id: 'apg8h9wh1pag',
            title: '245',
            type: '',
            isExpanded: false,
            level: 2,
            isActive: false,
          },
          {
            children: [],
            isRoot: false,
            id: 's2r0z9r5yzk8',
            title: '123456',
            type: '',
            isExpanded: false,
            level: 2,
            isActive: false,
          },
        ],
        isRoot: false,
        id: '48qco3vsw7kk',
        title: 'aaa',
        type: 'basemenu',
        isExpanded: false,
        styleType: 'submenu',
        pid: '5jsp3hcs0pfl',
        isActive: false,
        level: 1,
      },
    ],
    isRoot: true,
    id: '5jsp3hcs0pfl',
    title: 'ccc',
    type: 'group',
    isExpanded: false,
    styleType: 'group',
    pid: 0,
    isActive: false,
    level: 0,
  },
  {
    children: [
      {
        children: [],
        isRoot: false,
        id: 'h91bv4qwa4o2',
        path: '/test1101_hlz2igq_create',
        title: '222',
        type: 'link',
        isExpanded: false,
        styleType: 'menu',
        pid: 'vsnp42s72tq2',
        isActive: false,
        level: 1,
      },
    ],
    iconUrl:
      'https://6c6f-lowcode-8gr4tbore6df2c6a-1306806780.tcb.qcloud.la/weda-adminportal/upload/2022-01-13/767yld6u1arcnk25a9b8tntiwr8caad4_.jpeg?sign=12dee1e28f1ea202d65f725b8ed7dfdd&t=1642043932',
    isRoot: true,
    id: 'vsnp42s72tq2',
    title: 'bbb',
    type: 'basemenu',
    isExpanded: false,
    styleType: 'submenu',
    pid: 0,
    isActive: false,
    level: 0,
  },
  {
    children: [
      {
        children: [],
        isRoot: false,
        id: '44zntnen3rrd',
        title: 'eee',
        type: '',
        isExpanded: false,
        styleType: 'menu',
        pid: 'bnaav648605m',
        isActive: false,
        level: 1,
      },
    ],
    isRoot: true,
    id: 'bnaav648605m',
    title: 'ccc',
    type: 'basemenu',
    isExpanded: false,
    styleType: 'submenu',
    pid: 0,
    isActive: false,
    level: 0,
  },
  {
    children: [],
    id: 'u111',
    isRoot: true,
    id: 'u111',
    path: '/u111',
    title: '111',
    isExpanded: false,
    styleType: 'menu',
    type: '',
    pid: 0,
    isActive: false,
    level: 0,
  },
];
export const Tree = () => {
  return (
    <div>
      {data.map((i, index) => {
        return treeRender(i, index);
      })}
    </div>
  );
};
